org: beginnerstand
app: sht5-backend
service: sht5-backend

frameworkVersion: "2"

useDotenv: true

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
  lambdaHashingVersion: "20201221"
  stage: dev
  region: ap-southeast-1
  eventBridge:
    useCloudFormation: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "arn:aws:events:ap-southeast-1:*:event-bus/default"
        - Effect: Allow
          Action:
            - lambda:RemovePermission
          Resource: "arn:aws:events:ap-southeast-1:*:function:sht5-backend-dev-*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:ap-southeast-1:*:table/sht5-table"

package:
  individually: true
  patterns:
    - "!__pycache__/**"
    - "!*.zip"

functions:
  hello:
    image:
      name: appimage
      command:
        - handler.hello
    events:
      - http:
          path: /hello
          method: get
  verify:
    image:
      name: appimage
      command:
        - dfhandler.verify
    timeout: 120
    memorySize: 8192
    events:
      - eventBridge:
          pattern:
            detail-type:
              - IMAGE_O_UPLOADED
    environment:
      TEMPLATE_IMAGE: ${env:TEMPLATE_IMAGE}
  extractcolor:
    image:
      name: appimage
      command:
        - cvhandler.extractcolor
    timeout: 90
    memorySize: 4096
    events:
      - eventBridge:
          pattern:
            detail-type:
              - IMAGE_F_UPLOADED
  upload:
    runtime: nodejs14.x
    handler: nodehandler.upload
    events:
      - http:
          path: upload
          method: post
    environment:
      SUPABASE_URL: ${env:SUPABASE_URL}
      SUPABASE_KEY: ${env:SUPABASE_KEY}
      ADMIN_EMAIL: ${env:ADMIN_EMAIL}
      ADMIN_PASSWORD: ${env:ADMIN_PASSWORD}
  getitem:
    runtime: nodejs14.x
    handler: nodehandler.getitem
    events:
      - http:
          path: getitem
          method: get

custom:
  pythonRequirements:
    dockerizePip: non-linux

resources:
  Resources:
    DynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: sht5-table
