org: beginnerstand
app: sht5-backend
service: sht5-backend

frameworkVersion: "2"

useDotenv: true

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
  lambdaHashingVersion: "20201221"
  stage: dev
  region: ap-southeast-1

package:
  individually: true
  patterns:
    - "!__pycache__/**"
    - "!*.zip"

functions:
  hello:
    image:
      name: appimage
      command:
        - handler.hello
    events:
      - http:
          path: /hello
          method: get
  verify:
    image:
      name: appimage
      command:
        - dfhandler.verify
    timeout: 120
    events:
      - http:
          path: /verify
          method: post
  upload:
    runtime: nodejs14.x
    handler: nodehandler.upload
    events:
      - http:
          path: upload
          method: post
    environment:
      SUPABASE_URL: ${env:SUPABASE_URL}
      SUPABASE_KEY: ${env:SUPABASE_KEY}
      ADMIN_EMAIL: ${env:ADMIN_EMAIL}
      ADMIN_PASSWORD: ${env:ADMIN_PASSWORD}

custom:
  pythonRequirements:
    dockerizePip: non-linux
